# Generated by Django 4.1.7 on 2026-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('workout_id', models.CharField(max_length=100)),
                ('workout_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=100)),
                ('total_points', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('updated_at', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.CharField(max_length=100)),
                ('member_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=10)),
                ('created_at', models.CharField(max_length=100)),
                ('total_points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('points_per_unit', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
    ]
